package com.ali.design.chapter_02.v01;
//

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ConcreateStrategyB.java
//  @ Date : 2017/12/3
//  @ Author : 
//
//

public class ConcreateStrategyB implements Strategy {
	public void AlgrithmInterface() {
		System.out.println("ConcreateStrategyB");
	}
}
