package com.ali.design.chapter_02.v01;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ConcreateStrategyC.java
//  @ Date : 2017/12/3
//  @ Author : 
//
//




public class ConcreateStrategyC implements Strategy {
	public void AlgrithmInterface() {
		System.out.println("ConcreateStrategyC");
	}
}
