package com.ali.design.chapter_02.v01;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Strategy2.java
//  @ Date : 2017/12/3
//  @ Author : 
//
//




public interface Strategy {
	public void AlgrithmInterface();
}
